apiVersion: v1
kind: Config
clusters:
- name: "studentsurvey"
  cluster:
    server: "https://ec2-34-194-50-114.compute-1.amazonaws.com/k8s/clusters/c-m-8gqzghmk"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2VENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      GMwTkRNMApPVGt6TnpBZUZ3MHlOVEEwTVRFd05UTTROVGRhRncwek5UQTBNRGt3TlRNNE5UZGFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE56UTBNelE1T1RNM01Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRVRZTWc2ZTFsaVA0YQp2dGFnbkNNczl5eDg3a0Nhb1pDYXdNRTE2S\
      VRyaktGbjR4amgyMHhtcFp3czQzeHBDTmw0N2poZXhVVU1zcldNCkVMeDVTejNzdHFOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGS\
      2FKWVhXMkQ4YTExay81KzRzcU1kenZNcXZUTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFDaApMa\
      0xkUzRYNEFEbmt2cnBrNUhTUFhjTjNUTnpKQUFvN2tLdnBXbDZqVUFJZ1c5d3M0UW1veTJnK0JGZ\
      zZnZlNNClgxcW1qWUU1ZEswSG4ra0EyUWR4Tlo0PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "studentsurvey"
  user:
    token: "kubeconfig-user-cwttvkvrhb:vcb4gf68bpzfr42pmf9z6tqjc5f7nf6nswtn6ggh6ktdtk8l5rdx7d"


contexts:
- name: "studentsurvey"
  context:
    user: "studentsurvey"
    cluster: "studentsurvey"

current-context: "studentsurvey"
