apiVersion: v1
kind: Service
metadata:
  name: studentsurvey-service
  labels:
    app: studentsurvey
spec:
  type: NodePort
  selector:
    app: studentsurvey
  ports:
    - port: 8080         # the port exposed inside the cluster
      targetPort: 8080   # the port your container listens on
      protocol: TCP
      nodePort: 30116    # optional: pick a port in 30000–32767 (or omit to auto‑assign)
